### ISSUE TITLE
ignore generated files?

### ISSUE THREAD

**Issue by philjones88** [davguij/angular-npm-module-seed#1]
Do you think it should ignore the generated files like `src/index.ngsummary.json` and `src/seed.component.ngfactory.ts` for example?

Maybe add some more rules to the .gitignore ?

**Comment by davguij** [comment]
Nice suggestion. Thanks!

Actually, I don't like to see them in my local `src` folder either. It would be better to copy the whole source to a `.temp` folder and compiling from there, and then ditching it.

I'll try to find some time to tackle that later today.

**Comment by philjones88** [comment]
I have something like:

```
"outDir": "./aot/build"
```

and

```
"angularCompilerOptions": {
    "genDir": "aot"
    ....
}
```

then remove the `aot` directory at rebuild + exclude from git.

Therefore I don't see the generated files inside my source.

Something to try and experiment with?

**Comment by davguij** [comment]
Thanks for the suggestion, @philjones88. Moved generation to a `.tmp` folder. Much cleaner now.
