### ISSUE TITLE
Generate package.json in dist based on package.json in the root

### ISSUE THREAD

**Issue by prog110** [davguij/angular-npm-module-seed#2]
To make this compatible with tools like `semantic-release`, The `package.json` under `dist` folder needs to be generated from `package.json` as part of the build process.

This way plugins like [](https://github.com/semantic-release/semantic-release) can be used seemlessly with this seed.

If the `dist/package.json` is generated from the root, we can write a new script `publish` like this

```json
{
  "scripts": {
    "clean": "npm prune && rimraf .tmp && rimraf dist",
    "transpile": "ngc",
    "package": "rollup -c",
    "minify": "./node_modules/uglify-js/bin/uglifyjs dist/bundles/ng2-loading-bar.umd.js --screw-ie8 --compress --mangle --comments --output dist/bundles/ng2-loading-bar.umd.min.js",
    "copy": "cpx './package-dist.json' dist && renamer --find 'package-dist.json' --replace 'package.json' ./dist/*",
    "build": "npm run clean && npm run transpile && npm run package && npm run minify && npm run copy",
    "publish": "semantic-release pre && npm build && npm publish dist && semantic-release post"
  }
}
```

The `publish` script will

1. Generates the version based on commits & updates root `package.json` in the bulid machine(travis)
2. Generate umd package
3. Publish the package to npm
4. Pushes the above generated `package.json` to github
5. Generate releases & tags with messages combined from commit history
6. Push these tags to github

**Comment by davguij** [comment]
That's a nice suggestion, thanks. I didn't know about the `sematic-release` plugin!

If I understand you correctly, the `"copy"` script and the `package-dist.json` would be unnecessary because `semantic-release` would take care of that, correct?

If that's the case, when testing the module locally using `npm link`, the whole code should be `built` but not `publish`ed. Wouldn't that break the `npm link` since the `dist` folder wouldn't have its own `package.json`? 

Thanks again for your contribution!

**Comment by prog110** [comment]
I wrote a script that does this..

I've a [plugin](https://github.com/1tontech/ngx-http-interceptor/tree/angular2) that I've modified to use this & semantic-release plugin. Its publishing the versions properly with travis integration.

I'll submit a pull request for it later today

**Comment by prog110** [comment]
In the demo project that tests my angular plugin, I use `yarn add file:/<path to the plugin>/dist` to link the demo to the folder containing the development version

**Comment by thekalinga** [comment]
Please have a look at https://github.com/1tontech/ngx-http-interceptor/tree/angular2 for a project in which I'm using semantic release & this seed

**Comment by davguij** [comment]
> I've a plugin that I've modified to use this & semantic-release plugin. Its publishing the versions properly with travis integration.

I've taken a look at it and I understand you're basically using a Node.js app to save yourself from changing the `package.json` manually... Not bad, but I don't see it _that_ better as to implement it straight away. There might be a better way...

> In the demo project that tests my angular plugin, I use yarn add file:/<path to the plugin>/dist to link the demo to the folder containing the development version

Don't think Yarn is that mainstream yet, so I'm not keen on the idea of "forcing" anyone to use it.

> I'll submit a pull request for it later today

Feel free, I'll be happy to give it a look.

**Comment by prog110** [comment]
> I've taken a look at it and I understand you're basically using a Node.js app to save yourself from changing the package.json manually... Not bad, but I don't see it that better as to implement it straight away. There might be a better way...

Would you mind sharing your thoughts on that

> Don't think Yarn is that mainstream yet, so I'm not keen on the idea of "forcing" anyone to use it.

I'm not a JS developer myself. I worked mostly on server side in the past. Since I'm relatively to serious JS coding, I started using yarn it for the goodies it offers vs npm.

Otherwise, your regular flow with npm should not be affected irrespective of how package.json under dist is generated

> Feel free, I'll be happy to give it a look.

Looks like its better for me to submit one if we conclude on the approach.

Please let me know your thoughts

**Comment by davguij** [comment]
@thekalinga I've done a bit of research and I think I'll keep the whole thing manual by now. Digging a bit deeper, I feel than the `npm update` command is good enough for updating the distributed `package.json`. Thanks anyway for your valuable suggestions!
