### ISSUE TITLE
Provide external config

### ISSUE THREAD

**Issue by ghost** [davguij/angular-npm-module-seed#3]
First of all, nice job making this seed. 
I have just 2 small doubts.

The first is, if a service of the module uses the http service how can i made the factory providing that
```
export function seedServiceFactory() {
    return new SeedService();
}
export function authServiceFactory() {
    return new AuthenticationService(//parameter http module);
}

@NgModule({
    imports: [CommonModule],
    providers: [
        {provide: SeedService, useFactory: seedServiceFactory},
        {provide: AuthenticationService, useFactory: authServiceFactory}
    ],
    declarations: [SeedComponent],
    exports: [SeedComponent]
})
export class SeedModule {
}
```
The second is, I would like to do a module to encapsulate my services but depending on the app that use this external module I need diferent configuration for things like endpoints or stuff like that.
I have already done a configService to provide my configuration in my app. My question is, is there any way i can send this service to the module just once, so that the the external module can use it. Like if i inject this service to the module

**Comment by davguij** [comment]
> The first is, if a service of the module uses the http service how can i made the factory providing that

You don't need to do that. It's much easier. Just import the `HttpModule` into your module, the import `Http` into your services and that's it! Also, make sure you include `@angular/http` as a `peerDependency` into your `package.json.`

> My question is, is there any way i can send this service to the module just once, so that the the external module can use it. Like if i inject this service to the module

Have never done that, but the idea is to pass your configuration with the `forRoot() `method when importing the module. You might want to take a look here: [https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root)

**Comment by ghost** [comment]
Thanks, It works.
Regarding the second part I will try to do it.

Thanks again, it is really useful
