### ISSUE TITLE
Custom typings are not copied to dist folder

### ISSUE THREAD

**Issue by vrudikov** [davguij/angular-npm-module-seed#6]
Hi. Much appreciate your work. It's definitely easy to write Angular 2 modules with this project
So my question is: what if i have custom typings "somename.d.ts".
As for now my typings are ignored by compiler at all.
Here is the my fork of ng2-alt-summernote project
[ng4-summernote](https://github.com/vrudikov/ng4-summernote)

As you can see i have "summernote.d.ts" file there and i included it into all possible places: tsconfig.json, package.json, etc...

**Comment by davguij** [comment]
I have close to zero experience with custom typings, to be honest.

However, have you tried to use [Typings](https://github.com/typings/typings) and then to include the custom .d.ts in your project as explained [here](http://stackoverflow.com/questions/37641960/typescript-how-to-define-custom-typings-for-installed-npm-package)?

Hope that helps.

**Comment by vrudikov** [comment]
Yes. I saw that piece of information. Will check it out and if I find something - will leave comment here. Thank you very much for fast response

**Comment by davguij** [comment]
Cool. Feel free to drop me a line with your findings.

**Comment by vrudikov** [comment]
Sure. Thanks for support
