### ISSUE TITLE
Issue in package.json, Minify command does not work

### ISSUE THREAD

**Issue by BaamAadmi** [davguij/angular-npm-module-seed#7]
Hola David,
Thanks for this great "quickstart example" on publishing node_modules. I am currently using it to publish a project on my local repository. In doing so I found out an issue. 
It goes like,

> angular-npm-module-seed@1.0.0 minify D:\Angular_POC\angular-npm-module-seed-master
> ./node_modules/uglify-js/bin/uglifyjs dist/bundles/npm-module-seed.umd.js --screw-ie8 --compress --mangle --comments --output dist/bundles/npm-module-seed.umd.min.js

> 
> '.' is not recognized as an internal or external command,
> operable program or batch file.

This is basically because of following line
`"minify": "./node_modules/uglify-js/bin/uglifyjs dist/bundles/npm-machao-component.umd.js --screw-ie8 --compress --mangle --comments --output dist/bundles/npm-machao-component.umd.min.js",`

My OS: Windows 7 64bit
Node -v: 6.10.2

Let me know if you have a workaround for the same. I will look at it as well when all my publish is successful. 

Also,
It would be great if you include "how do we use published components/module in the target location" in the documentation as well. 

Cheers,
Sudeep Rane

**Comment by davguij** [comment]
Probably just removing the "./" in Win systems would do the trick...

**Comment by BaamAadmi** [comment]
I tried this but no luck. I even tried following code, 

`"minify": "uglifyjs dist/bundles/npm-module-seed.umd.js --o dist/bundles/npm-module-seed.umd.min.js",`

But that didnt work either, gave me parser errors.  So I am going to keep minification on hold for a while. :)

**Comment by nipuna-g** [comment]
@BaamAadmi  Try `"minify": "node ./node_modules/uglify-js/bin/uglifyjs dist/bundles/npm-machao-component.umd.js --screw-ie8 --compress --mangle --comments --output dist/bundles/npm-machao-component.umd.min.js"`

**Comment by jaskevs** [comment]
@nipuna777 That did the trick, thank you
